### ISSUE TITLE
Conserved TFBS Jaspar 2020 Downloading

### ISSUE THREAD

**Issue by himanshusingh2018** [asntech/jaspar#1]
Dear Dr. Khan,
I wonder, how can I download Conserved TFBS from Jaspar2020. Your help is appreciated.
Thanks
Himanshu
Aix Marseille University
Himanshu

**Comment by asntech** [comment]
Hi Himanshu,

Thanks for your interest in jaspar. We don’t provide any list of conserved TFBSs, but please feel free to send your request here: https://groups.google.com/forum/#!forum/jaspar

Maybe someone from the team may help you. Thanks!

Best,
Aziz

**Comment by himanshusingh2018** [comment]
Thank you very much for the information.
